name: Build (Release)

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Tags
        type: string
        required: true
        default: "latest,1.6"
      wine_version:
        description: Wine Version
        type: string
        required: true
        default: 6.0.3
      beeup_download_url:
        description: Bee-Up Download URL
        type: string
        required: true
        default: "https://bee-up.omilab.org/files/tool-installer/Bee-Up_1.6_64-bit_macOS-prototype.zip"

jobs:
  build-release:
    uses: ./.github/workflows/build.yml
    with:
      base_image: docker.io/library/ubuntu:focal
      image_name: beeup
      tags: ${{ inputs.tags }}
      platforms: linux/amd64
      wine_version: ${{ inputs.wine_version }}
      beeup_download_url: ${{ inputs.beeup_download_url }}
    secrets:
      username: ${{ github.actor }}
      token: ${{ secrets.GITHUB_TOKEN }}
